In [4]:
# get data_cluster
import pandas as pd 

# import json
# with open("/data/home/chensh/projects/LLM_router/datasets/split2_model7_cluster/gsm8k-train.json", 'r') as f:
#     gsm8k_data = json.load(f)

gsm8k_data = pd.read_json("/data/home/chensh/projects/LLM_router/datasets/split2_model7_cluster/gsm8k-train.json")

In [6]:
gsm8k_data["cluster_id"].unique()

array([1, 4, 0, 2])

In [8]:
gsm8k_data[gsm8k_data["cluster_id"]==0]

,question,scores,cluster_id
55,There are 25 roses in a garden. There are 40 t...,"{'mistralai/Mistral-7B-v0.1': 0.5, 'meta-math/...",0
184,"After tests in California, the total number of...","{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",0
235,Max likes to collect model trains. He asks fo...,"{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",0
392,Naomi is doing the wash. First she makes piles...,"{'mistralai/Mistral-7B-v0.1': 1.0, 'meta-math/...",0
401,"Kimberley, Ela, and Houston all are sent to co...",{'mistralai/Mistral-7B-v0.1': 0.60000000000000...,0
494,"There is a 5,200 sq. ft. house and a 7,300 sq....",{'mistralai/Mistral-7B-v0.1': 0.60000000000000...,0
668,"A box is 8 inches in height, 10 inches in widt...",{'mistralai/Mistral-7B-v0.1': 0.30000000000000...,0
707,Melanie is making meatballs for dinner. The re...,"{'mistralai/Mistral-7B-v0.1': 0.5, 'meta-math/...",0
751,Harry is joining a marathon that's why he prac...,"{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",0
799,"There is a very large room that has 4 tables, ...",{'mistralai/Mistral-7B-v0.1': 0.30000000000000...,0
830,Forty percent of the students have elected to ...,"{'mistralai/Mistral-7B-v0.1': 0.9, 'meta-math/...",0
897,The perimeter of a square-shaped piece of pape...,{'mistralai/Mistral-7B-v0.1': 0.70000000000000...,0
928,"In a glee club, there are two times as many fe...","{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",0
953,Wendi brought home 4 chickens. After a few da...,"{'mistralai/Mistral-7B-v0.1': 0.1, 'meta-math/...",0

In [9]:
gsm8k_data[gsm8k_data["cluster_id"]==1]

,question,scores,cluster_id
0,Natalia sold clips to 48 of her friends in Apr...,"{'mistralai/Mistral-7B-v0.1': 1.0, 'meta-math/...",1
1,Weng earns $12 an hour for babysitting. Yester...,"{'mistralai/Mistral-7B-v0.1': 0.9, 'meta-math/...",1
2,Betty is saving money for a new wallet which c...,"{'mistralai/Mistral-7B-v0.1': 0.4, 'meta-math/...",1
3,"Julie is reading a 120-page book. Yesterday, s...","{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",1
4,James writes a 3-page letter to 2 different fr...,"{'mistralai/Mistral-7B-v0.1': 0.1, 'meta-math/...",1
...,...,...,...
992,Hannah is making banana bread. She needs to us...,"{'mistralai/Mistral-7B-v0.1': 1.0, 'meta-math/...",1
993,Rick has 130 cards. He decided to only keep 15...,"{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",1
994,Dean ordered 2 large pizzas that were each cut...,"{'mistralai/Mistral-7B-v0.1': 0.4, 'meta-math/...",1
995,"Josh and Anna were both born on August 17th, b...","{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",1
996,A club opens up and charges $20 to enter. Jam...,"{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",1

In [10]:
gsm8k_data[gsm8k_data["cluster_id"]==4]

,question,scores,cluster_id
7,Ken created a care package to send to his brot...,"{'mistralai/Mistral-7B-v0.1': 0.1, 'meta-math/...",4
8,Alexis is applying for a new job and bought a ...,"{'mistralai/Mistral-7B-v0.1': 0.2, 'meta-math/...",4
32,A car is driving through a tunnel with many tu...,{'mistralai/Mistral-7B-v0.1': 0.70000000000000...,4
33,"To make pizza, together with other ingredients...","{'mistralai/Mistral-7B-v0.1': 0.9, 'meta-math/...",4
61,A bear is preparing to hibernate for the winte...,{'mistralai/Mistral-7B-v0.1': 0.30000000000000...,4
...,...,...,...
919,Aisha enjoys listening to music on her mp3 pla...,"{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",4
946,Ruby is taking dance lessons. They cost $75 fo...,"{'mistralai/Mistral-7B-v0.1': 0.1, 'meta-math/...",4
997,Ittymangnark and Kingnook are an Eskimo couple...,"{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",4
998,Lydia has a small pool she uses to bathe her d...,"{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",4
999,Miss Grayson's class raised $50 for their fiel...,{'mistralai/Mistral-7B-v0.1': 0.70000000000000...,4

In [11]:
gsm8k_data[gsm8k_data["cluster_id"]==2]

,question,scores,cluster_id
83,Paityn has 20 red hats and 24 blue hats. Her f...,"{'mistralai/Mistral-7B-v0.1': 0.2, 'meta-math/...",2
116,Valerie needs to put stamps on the envelopes s...,"{'mistralai/Mistral-7B-v0.1': 0.0, 'meta-math/...",2
148,Winwin won $50 in a lottery. She paid 20% for ...,"{'mistralai/Mistral-7B-v0.1': 0.9, 'meta-math/...",2
154,Ariella has $200 more in her son's saving acco...,"{'mistralai/Mistral-7B-v0.1': 0.2, 'meta-math/...",2
161,The town’s annual budget totals $32 million. I...,"{'mistralai/Mistral-7B-v0.1': 0.4, 'meta-math/...",2
223,Andy and Bob went to the canteen to buy snacks...,"{'mistralai/Mistral-7B-v0.1': 0.1, 'meta-math/...",2
341,Samuel swept the porch and cleared nine-tenths...,"{'mistralai/Mistral-7B-v0.1': 0.1, 'meta-math/...",2
383,Anna baked 60 cupcakes. She gives away 4/5 of ...,"{'mistralai/Mistral-7B-v0.1': 0.1, 'meta-math/...",2
612,Ali is collecting bottle caps. He has 125 bott...,"{'mistralai/Mistral-7B-v0.1': 0.9, 'meta-math/...",2
685,There are some kids in camp. Half of the kids ...,"{'mistralai/Mistral-7B-v0.1': 0.1, 'meta-math/...",2
961,Johnny TV makes 25 percent more movies than L&...,{'mistralai/Mistral-7B-v0.1': 0.70000000000000...,2

In [86]:
# load sample list
import os
import sys
sys.path.append("..")
os.environ["CUDA_VISIBLE_DEVICES"]="4"
from openTSNE import TSNE
import torch

from train_router_mdeberta_v4 import RouterDataset, RouterModule
from torch.utils.data import Dataset, DataLoader, ConcatDataset
from transformers import T5EncoderModel, T5Tokenizer, AutoTokenizer, DebertaV2Model

dataset_paths = ["../datasets/split2_model7_cluster/gsm8k-train.json",]

data_types = ["multi_attempt"]

# dataset_paths = ["../../datasets/split2_model7/gsm8k-train.json"]
# data_types = ["multi_attempt"]

tokenizer = AutoTokenizer.from_pretrained("/data/home/chensh/data/huggingface_model/microsoft/mdeberta-v3-base", truncation_side='left', padding=True)
encoder_model = DebertaV2Model.from_pretrained("/data/home/chensh/data/huggingface_model/microsoft/mdeberta-v3-base").to("cuda")
trained_router_path = "/data/home/chensh/projects/LLM_router/logs/router_debug/ablation_clw/clw_1/slw_0_clw_1_clw_2_0_cos_tk_3_lk_3_lr_5e-5_step_1000_t_1_seed_5/best_training_model.pth"

# trained_router_path = "/data/home/chensh/projects/LLM_router/logs/router_debug/ablation_slw/slw_0/slw_0_clw_0_clw_2_0_cos_tk_3_lk_3_lr_5e-5_step_1000_t_1_seed_5/best_training_model.pth"

router_datasets = [RouterDataset(data_path, data_type=data_types[i], dataset_id=i) for i, data_path in enumerate(dataset_paths)]
for router_dataset in router_datasets:
    router_dataset.register_tokenizer(tokenizer)
router_dataset = ConcatDataset(router_datasets)
router_dataloader = DataLoader(router_dataset, batch_size=64)


router_model = RouterModule(encoder_model, hidden_state_dim=768, node_size=len(router_datasets[0].router_node), similarity_function="cos").to("cpu")
router_model.to('cuda')

state_dict = torch.load(trained_router_path)
router_model.load_state_dict(state_dict)


# get predicted label 
all_hidden_states = []
dataset_set_ids = []
cluster_ids = []
predicts = []
with torch.no_grad():
    for i, batch in enumerate(router_dataloader):
        input, _, dataset_id, cluster_id = batch
        input.to("cuda")
        predict, hidden_states = router_model(**input)
        dataset_set_ids.append(dataset_id)
        cluster_ids.append(cluster_id)
        predicts.append(predict)
        all_hidden_states.append(hidden_states)


all_hidden_states = torch.concat(all_hidden_states)
predicts = torch.concat(predicts)
cluster_ids = torch.concat(cluster_ids).numpy() 
_, max_index = torch.max(predicts, dim=1)

/data/home/chensh/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:550: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

In [87]:
cos_sim = torch.nn.functional.cosine_similarity(all_hidden_states.unsqueeze(0),all_hidden_states.unsqueeze(1), dim=-1)
min_value, index_1 = torch.min(cos_sim, dim=0)
min_value, index_2 = torch.min(min_value, dim=0)
print(index_1[index_2])
print(index_2)

tensor(304, device='cuda:0')
tensor(148, device='cuda:0')

In [88]:
cos_sim[24][2]

tensor(0.9982, device='cuda:0')

In [71]:
import pandas as pd 

gsm8k_data = pd.read_json("/data/home/chensh/projects/LLM_router/datasets/split2_model7_cluster/gsm8k-train.json")

In [77]:
print(gsm8k_data.iloc[24]["question"])

Mary does her grocery shopping on Saturday. She does her shopping only at a specific store where she is allowed a credit of $100, which must be paid in full before her next shopping trip. That week she spent the full credit limit and paid $15 of it on Tuesday and $23 of it on Thursday. How much credit will Mary need to pay before her next shopping trip?

In [84]:
print(gsm8k_data.iloc[2]["question"])

Betty is saving money for a new wallet which costs $100. Betty has only half of the money she needs. Her parents decided to give her $15 for that purpose, and her grandparents twice as much as her parents. How much more money does Betty need to buy the wallet?

In [85]:
cos_sim[24]

tensor([-0.3403,  0.2301, -0.4589, -0.4729, -0.2976, -0.3218,  0.0134, -0.1686,
        -0.2833,  0.0791, -0.3007, -0.2608, -0.3817,  0.0446,  0.2888, -0.0171,
        -0.2819, -0.5035, -0.3761,  0.0428, -0.3451, -0.2518, -0.5875,  0.6842,
         1.0000,  0.1213, -0.3730, -0.3434, -0.3445, -0.4625, -0.1139, -0.2239,
        -0.4576, -0.4943, -0.4612, -0.6138, -0.0426,  0.0172,  0.0507, -0.4699,
        -0.3279, -0.3585, -0.4881, -0.1283,  0.1213, -0.3007,  0.0091, -0.3968,
        -0.2988,  0.0105, -0.3889,  0.0015, -0.4850, -0.3409, -0.4950, -0.2717,
        -0.4109, -0.3903, -0.2618, -0.5807, -0.4975, -0.3321, -0.3684,  0.0248,
        -0.0663, -0.5027, -0.3894, -0.4372, -0.3676, -0.1330, -0.4797, -0.4723,
        -0.4442, -0.5773,  0.1999,  0.0146, -0.3012, -0.2165,  0.1645, -0.0526,
         0.2874,  0.1970, -0.3479, -0.1046, -0.1716,  0.0448, -0.4915, -0.3090,
        -0.4778,  0.7747, -0.2673,  0.1629, -0.4959, -0.5116, -0.4683, -0.0174,
        -0.4428, -0.4298, -0.5216,  0.1006,  0.0471, -0.3491,  0.0105, -0.3899,
        -0.3245, -0.3525, -0.2595, -0.0013, -0.1565, -0.4757, -0.3686,  0.7708,
        -0.4322, -0.4956,  0.0276], device='cuda:0')

tensor([-0.3403,  0.2301, -0.4589, -0.4729, -0.2976, -0.3218,  0.0134, -0.1686,
        -0.2833,  0.0791, -0.3007, -0.2608, -0.3817,  0.0446,  0.2888, -0.0171,
        -0.2819, -0.5035, -0.3761,  0.0428, -0.3451, -0.2518, -0.5875,  0.6842,
         1.0000,  0.1213, -0.3730, -0.3434, -0.3445, -0.4625, -0.1139, -0.2239,
        -0.4576, -0.4943, -0.4612, -0.6138, -0.0426,  0.0172,  0.0507, -0.4699,
        -0.3279, -0.3585, -0.4881, -0.1283,  0.1213, -0.3007,  0.0091, -0.3968,
        -0.2988,  0.0105, -0.3889,  0.0015, -0.4850, -0.3409, -0.4950, -0.2717,
        -0.4109, -0.3903, -0.2618, -0.5807, -0.4975, -0.3321, -0.3684,  0.0248,
        -0.0663, -0.5027, -0.3894, -0.4372, -0.3676, -0.1330, -0.4797, -0.4723,
        -0.4442, -0.5773,  0.1999,  0.0146, -0.3012, -0.2165,  0.1645, -0.0526,
         0.2874,  0.1970, -0.3479, -0.1046, -0.1716,  0.0448, -0.4915, -0.3090,
        -0.4778,  0.7747, -0.2673,  0.1629, -0.4959, -0.5116, -0.4683, -0.0174,
        -0.4428, -0.4298, -0.5216,  0.1006,  0.0471, -0.3491,  0.0105, -0.3899,
        -0.3245, -0.3525, -0.2595, -0.0013, -0.1565, -0.4757, -0.3686,  0.7708,
        -0.4322, -0.4956,  0.0276], device='cuda:0')